on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Run "wsl --list --online"
      run: wsl --list --online
    
    - name: Run "wsl --install Ubuntu"
      run: wsl --install Ubuntu

    - name: Run "wsl --status"
      run: wsl --status
    
    - name: Run "bash --version"
      run: bash --version
    
    - name: Run "wsl whoami"
      run: wsl whoami
