on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Run "wsl --list --online"
      #shell: powershell
      run: wsl --list --online
    - name: Run "wsl --status"
      #shell: powershell
      run: wsl --status
    - name: Run "bash --version"
      #shell: powershell
      run: bash --version
    - name: Run "wsl whoami"
      #shell: powershell
      run: wsl whoami
