on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Run "wsl --install Ubuntu"
      run: wsl --install --distribution Ubuntu

    - name: Run "wsl --list --all"
      run: wsl --list --all

    - name: Run "bash --version"
      run: bash --version
    
    - name: Run "wsl whoami"
      run: wsl --distribution Ubuntu whoami

    - name: Run "wsl --status"
      run: wsl --status
