on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Run "wsl --set-default-version 2"
      run: wsl --set-default-version 2

    - name: Run "wsl --list --online"
      run: wsl --list --online
    
    - name: Run "wsl --install Ubuntu"
      run: wsl --install --distribution Ubuntu

    - name: Run "wsl --list --online"
      run: wsl --list --online

    - name: Run "wsl --status"
      run: wsl --status
    
    - name: Run "bash --version"
      run: bash --version
    
    - name: Run "wsl whoami"
      run: wsl whoami
