on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
    - name: Run the script
      shell: powershell
      run: |
        wsl --status
        bash --version
        ubuntu whoami
