name: ci
on: push
jobs:
  ci:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Run the script
      run: |
        powershell
        Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
        wsl
        bash
        ubuntu
