on: push
name: main

jobs:
  main:
    runs-on: windows-latest
    steps:
    - name: Check out the source code
      uses: actions/checkout@v3
    - name: Run the script
      shell: powershell
      run: |
        bash --version
        Enable-WindowsOptionalFeature -Online -NoRestart -FeatureName Microsoft-Windows-Subsystem-Linux
        Dism /online /Get-FeatureInfo /FeatureName:Microsoft-Windows-Subsystem-Linux
        #wsl
        bash --version
        #ubuntu
